include:
  - path : ./supabase/docker/docker-compose.yml
    env_file: ./supabase/docker/.env

services:
  app:
    container_name: ${APP_NAME}
    build: 
      context: ./web/
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: pnpm run dev --host
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-developpement}
      HTTP_APP_PORT: ${HTTP_APP_PORT:-5173}
      APP_PATH: ${APP_PATH:-/var/www/app/}
    ports:
      - ${HTTP_APP_PORT}:5173
      - ${HTTPS_APP_PORT}:8443
    volumes:
      - ./web/app/:${APP_PATH:-/var/www/app/}
      - ${APP_PATH:-/var/www/app/}/node_modules

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080
    depends_on:
      - db # declared in ./supabase/docker/docker-compose.yml
